//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novea2._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public string MADG { get; set; }
        public Nullable<System.DateTime> NGAYDG { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> RATE { get; set; }
        public string MAND_KHACH { get; set; }
        public string MASP { get; set; }
    
        public virtual KHACH KHACH { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
